local wezterm = require("wezterm")
local config = wezterm.config_builder()

-- Theme: tokyo-night
-- Generated by theme switcher
config.colors = {
    foreground = "#a9b1d6",
    background = "#1a1b26",
    cursor_bg = "#a9b1d6",
    cursor_fg = "#1a1b26",
    cursor_border = "#a9b1d6",
    selection_bg = "#292e42",
    selection_fg = "#a9b1d6",

    ansi = {
        "#1a1b26",      -- black
        "#f7768e",             -- red
        "#9ece6a",           -- green
        "#e0af68",          -- yellow
        "#7aa2f7",            -- blue
        "#ad8ee6",         -- magenta
        "#449dab",            -- cyan
        "#414868",           -- white
    },
    brights = {
        "#414868",           -- bright black
        "#ff7a93",      -- bright red
        "#b9f27c",    -- bright green
        "#ff9e64",   -- bright yellow
        "#7da6ff",     -- bright blue
        "#bb9af7", -- bright magenta
        "#0db9d7",     -- bright cyan
        "#a9b1d6",      -- bright white
    },
}

-- Font configuration
config.font = wezterm.font("FiraMono Nerd Font Mono", { weight = "Regular" })
config.font_size = 13.0
config.line_height = 1.0
config.freetype_load_target = "Light"
config.force_reverse_video_cursor = true

config.adjust_window_size_when_changing_font_size = false

-- Tab bar
config.hide_tab_bar_if_only_one_tab = true
config.use_fancy_tab_bar = false
config.show_tabs_in_tab_bar = false
config.show_new_tab_button_in_tab_bar = false

-- Transparency
config.window_background_opacity = 0.93
config.macos_window_background_blur = 8

-- Cursor
config.cursor_blink_rate = 500
config.default_cursor_style = "BlinkingBlock"
config.cursor_blink_ease_in = "Constant"
config.cursor_blink_ease_out = "Constant"

-- Window
config.window_decorations = "RESIZE"
config.window_padding = {
    left = 0,
    right = 0,
    top = 0,
    bottom = 0,
}

config.enable_wayland = false

return config
