local wezterm = require("wezterm")
local config = wezterm.config_builder()

-- Theme: hackerman
-- Generated by theme switcher
config.colors = {
    foreground = "#ddf7ff",
    background = "#0B0C16",
    cursor_bg = "#ddf7ff",
    cursor_fg = "#0B0C16",
    cursor_border = "#ddf7ff",
    selection_bg = "#1f253a",
    selection_fg = "#ddf7ff",

    ansi = {
        "#0B0C16",      -- black
        "#50f872",             -- red
        "#4fe88f",           -- green
        "#50f7d4",          -- yellow
        "#829dd4",            -- blue
        "#86a7df",         -- magenta
        "#7cf8f7",            -- cyan
        "#2d3450",           -- white
    },
    brights = {
        "#2d3450",           -- bright black
        "#85ff9d",      -- bright red
        "#9cf7c2",    -- bright green
        "#a4ffec",   -- bright yellow
        "#c4d2ed",     -- bright blue
        "#cddbf4", -- bright magenta
        "#d1fffe",     -- bright cyan
        "#ddf7ff",      -- bright white
    },
}

-- Font configuration
config.font = wezterm.font("FiraMono Nerd Font Mono", { weight = "Regular" })
config.font_size = 13.0
config.line_height = 1.0
config.freetype_load_target = "Light"
config.force_reverse_video_cursor = true

config.adjust_window_size_when_changing_font_size = false

-- Tab bar
config.hide_tab_bar_if_only_one_tab = true
config.use_fancy_tab_bar = false
config.show_tabs_in_tab_bar = false
config.show_new_tab_button_in_tab_bar = false

-- Transparency
config.window_background_opacity = 0.93
config.macos_window_background_blur = 8

-- Cursor
config.cursor_blink_rate = 500
config.default_cursor_style = "BlinkingBlock"
config.cursor_blink_ease_in = "Constant"
config.cursor_blink_ease_out = "Constant"

-- Window
config.window_decorations = "RESIZE"
config.window_padding = {
    left = 0,
    right = 0,
    top = 0,
    bottom = 0,
}

config.enable_wayland = false

return config
