local wezterm = require("wezterm")
local config = wezterm.config_builder()

-- Theme: catppuccin
-- Generated by theme switcher
config.colors = {
    foreground = "#cdd6f4",
    background = "#1e1e2e",
    cursor_bg = "#cdd6f4",
    cursor_fg = "#1e1e2e",
    cursor_border = "#cdd6f4",
    selection_bg = "#45475a",
    selection_fg = "#cdd6f4",

    ansi = {
        "#1e1e2e",      -- black
        "#f38ba8",             -- red
        "#a6e3a1",           -- green
        "#f9e2af",          -- yellow
        "#89b4fa",            -- blue
        "#f5c2e7",         -- magenta
        "#94e2d5",            -- cyan
        "#585b70",           -- white
    },
    brights = {
        "#585b70",           -- bright black
        "#f38ba8",      -- bright red
        "#a6e3a1",    -- bright green
        "#f9e2af",   -- bright yellow
        "#89b4fa",     -- bright blue
        "#f5c2e7", -- bright magenta
        "#94e2d5",     -- bright cyan
        "#cdd6f4",      -- bright white
    },
}

-- Font configuration
config.font = wezterm.font("FiraMono Nerd Font Mono", { weight = "Regular" })
config.font_size = 13.0
config.line_height = 1.0
config.freetype_load_target = "Light"
config.force_reverse_video_cursor = true

config.adjust_window_size_when_changing_font_size = false

-- Tab bar
config.hide_tab_bar_if_only_one_tab = true
config.use_fancy_tab_bar = false
config.show_tabs_in_tab_bar = false
config.show_new_tab_button_in_tab_bar = false

-- Transparency
config.window_background_opacity = 0.93
config.macos_window_background_blur = 8

-- Cursor
config.cursor_blink_rate = 500
config.default_cursor_style = "BlinkingBlock"
config.cursor_blink_ease_in = "Constant"
config.cursor_blink_ease_out = "Constant"

-- Window
config.window_decorations = "RESIZE"
config.window_padding = {
    left = 0,
    right = 0,
    top = 0,
    bottom = 0,
}

config.enable_wayland = false

return config
