services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: parq
      TZ: America/New_York
    volumes:
      - /root/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d parq"]
      interval: 10s
      timeout: 5s
      retries: 5
